const SET_WIDTH = 'SET_WIDTH';
const SET_HEIGHT = 'SET_HEIGHT';
const SET_BLEED = 'SET_BLEED';
const SET_STROKEWIDTH = 'SET_STROKEWIDTH';
const SET_BASE = 'SET_BASE';
const SET_RATIO = 'SET_RATIO';
const SET_BACKGROUND = 'SET_BACKGROUND';
const SET_STROKECOLOR = 'SET_STROKECOLOR';
const SET_SUNX = 'SET_SUNX';
const SET_SUNY = 'SET_SUNY';
const SET_SUNRADIUS = 'SET_SUNRADIUS';

export {
  SET_WIDTH,
  SET_HEIGHT,
  SET_BLEED,
  SET_STROKEWIDTH,
  SET_BASE,
  SET_RATIO,
  SET_BACKGROUND,
  SET_STROKECOLOR,
  SET_SUNX,
  SET_SUNY,
  SET_SUNRADIUS
};